// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdzopbxjmedvsiktoezl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkem9wYnhqbWVkdnNpa3RvZXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzI0ODEsImV4cCI6MjA2MjA0ODQ4MX0.3Vuow3a_t2s6w0wuVcoi5iX5DRJQjZf4zdpFuMAjQzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);